version: "3.7"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_DB: "${PG_DB}"
    ports:
      - "5432:${PG_PORT}"
